### ISSUE TITLE
Format JSON Payload to Remove Carriage Return

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#105]
We need to send http request to GraphQL via the Flask API in order to intercept custom mutations and execute them (executeBatch, testDataSource). In order to do so, the web app should format the JSON payload to make sure it does not contain carriage returns.

Current structure generated by Appollo:
```json
{
  "operationName":null,
  "variables":{},
  "query":"{
      allIndicators{
          nodes{
              id
              name
              description
              executionOrder
              flagActive
              createdDate
              updatedDate
              indicatorTypeId
              __typename
          }
      __typename
      }
  }"
}
```

Ideal structure:
```json
{
  "operationName":null,
  "variables":{},
  "query":"{allIndicators{nodes{id,name,description,executionOrder,flagActive,createdDate,updatedDate,indicatorTypeId,__typename}__typename}}"
}
```

**Comment by alexisrolland** [comment]
I've rebuilt and rerun the containers with the latest updates from`development` branch. The web app now works with Flask API thank to `flask-cors` which has been added. I'm closing this issue.
