### ISSUE TITLE
Design Roles and Permissions Strategy

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#112]
As a user of the data quality framework, I would like to have a clearly defined roles and permissions strategy. The solution should allow easy management of users permissions.

Some ideas:
- Roles and permissions should support teams concept to allow multiple teams to use the same instance
- Read and write access should be defined at entity (indicator, data source, etc...) and records level
- Possibly reuse roles and permissions mechanisms from PostgreSQL database

Create new user stories for the implementation of Roles and Permissions once this story is completed.

**Comment by alexisrolland** [comment]
Roles and permissions implemented in dev. Some changes are still required:
- Document user, user group, roles management
- Prevent standard user to read data source password
- Prevent standard user to insert, update, delete data source
- Implement referential integrity for user group columns
