### ISSUE TITLE
Implement visible form field selection

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#116]

**Comment by alexisrolland** [comment]
@vilkazz Could you please describe what's the intention for this user story?
Thanks

**Comment by vilkazz** [comment]
I think i'll close it. I had a veeery nice to have feature in mind here, but now i think it would be a waste of time and effort at this stage.

The idea was to allow user to reorder form fields, hide unwanted fields and other similar ux candies.
