### ISSUE TITLE
Separate components and containers

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#121]

**Comment by alexisrolland** [comment]
@vilkazz  Could you please describe what's the intention for this user story?
Thanks

**Comment by vilkazz** [comment]
Logically, in react you want every component to be as simple as possible. Thus if you have a list of items, say an indicator list, you want to have a table container, having a list of table row containers, that respectively hold a list of table cell components. 

You can read more on it in https://medium.com/@learnreact/container-components-c0e67432e005

**Comment by vilkazz** [comment]
Closed as List component was fully rewritten
