### ISSUE TITLE
Investigate How to Use Public/Private Keys to Manage Data Source Passwords

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#123]
As a user of the data quality framework I would to have a secure way to manage passwords for data sources created in the tool. Most likely using a combination of public and private keys to encrypt / decrypt passwords.

**Comment by alexisrolland** [comment]
I think we can do simpler. Here is a tutorial how to manage password encryption in PostgreSQL:
https://x-team.com/blog/storing-secure-passwords-with-postgresql

**Comment by alexisrolland** [comment]
Solution implemented with function PGP_SYM_ENCRYPT from pgcrypto extension
