### ISSUE TITLE
Update Scripts Dockerfile to Support Connection to Hive

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#124]
As a user of the data quality framework, I would like to be able to compute data quality indicators on Hive database.

- [x] To create a test container db-hive including test data
- [x] To update the scripts Dockerfile in order to include Hive ODBC driver (Cloudera, Hortonworks, other?)
- [x] To update Data Source script to ensure connectivity to Hive database

**Comment by alexisrolland** [comment]
https://github.com/mobydq/mobydq/pull/227
