### ISSUE TITLE
Update Scripts Dockerfile to Support Connection to Oracle

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#127]
As a user of the data quality framework, I would like to be able to compute data quality indicators on Oracle database.
- [ ] To create a test container db-oracle including test data
- [ ] To update the scripts Dockerfile in order to include Oracle ODBC driver
- [ ] To update Data Source script to ensure connectivity to Oracle database

**Comment by alexisrolland** [comment]
In progress:
- Dockerfile is done
- Driver is added to the repo
- Database file

**Comment by alexisrolland** [comment]
This is finally done... supporting Oracle was a nightmare!
