### ISSUE TITLE
Implement Automated Unit Tests for Flask API

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#130]
As a developer on the data quality framework, I would like to have automated unit tests implemented for all methods in the Python scripts. This would allow to monitor potential regression issues when delivering new releases.
- [ ] api, graphql endpoint
- [x] api, health endpoint

**Comment by alexisrolland** [comment]
Unit test implemented on health check endpoint. Two unit tests to be implemented on GraphQL endpoint:
* one query
* one mutation

**Comment by alexisrolland** [comment]
This can be implemented once the custom authentication is implemented. Otherwise it is not possible to test endpoint using the current OAuth authentication.
