### ISSUE TITLE
Implement SSL Encryption for GraphQL API

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#134]
As a user of the data quality framework, I would like the Flask API to use SSL encryption. In particular to ensure login and passwords sent over the network are not captured by third parties.

**Comment by alexisrolland** [comment]
If the access to the GraphQL API is restricted to containers in the Docker network, this might not be necessary. We need to discuss the need for the web app to access the GraphQL API directly or not. See issue #138
