### ISSUE TITLE
Restrict Access to GraphQL API for Flask API Only

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#138]
As a developer on the data quality framework, I would like the access to the GraphQL API to be restricted in order to prevent users without proper permissions to perform forbidden operations on the database.

When logging in with flask api, we will return a uniques access token to the user.
This token will have to be passed as auth data to graphql.
https://medium.com/the-graphqlhub/graphql-and-authentication-b73aed34bbeb for reference.
---------------------- ­
Simas Joneliunas on Thursday Aug 16, 2018 03:25 AM:
Ill take ownership of it a bit later into the project. First i want to have some frontend done so we could actually test the auth.
---------------------- ­
Alexis ROLLAND on Monday Sep 03, 2018 12:16 AM:
I changed the docker compose prod configuration to prevent access to GraphQL from the outside of the Docker network. Only the Flask API and the App have their ports exposed. So I’m not sure this is still required.
---------------------- ­
Simas Joneliunas on Monday Sep 03, 2018 12:24 AM:
Uh, the website (app container) is running react.
Thus ALL of the calls will be coming from outside.
We cant restrict it like that.
---------------------- ­
Alexis ROLLAND on Monday Sep 03, 2018 12:30 AM:
Hum I see, we can reverse the change... otherwise one work around I’m thinking could be for react to send the requests to the Flask API which can already route them to GraphQL and return the same result. In theory just changing the base URL to http://server/data-quality/api/graphql should work. And then we can manage auth and permissions with Flask

**Comment by alexisrolland** [comment]
This can be done simply by removing the port mapping in docker-composer.yml for the graphql service.

**Comment by alexisrolland** [comment]
Port mapping removed from `docker-compose.yml` and added to `docker-compose.dev.yml`
