### ISSUE TITLE
Update database to incorporate new features

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#156]
- [x] Update schema SQL
- [x] Update documentation with new schema
- [x] Update test data SQL
- [x] Create db functions if required

**Comment by PascalHonegger** [comment]
Discuss the use of global / group specific roles. Maybe only allow the roles "user" and "super admin" globally to make life easier.

**Comment by alexisrolland** [comment]
New view on pg_roles table to be created in order to fetch the user group of the user

**Comment by Moeby** [comment]
Some functions still need to be implemented:

- getAllGroups 
- getUserGroups
- getPrivilegesForGroup
- setUser
