### ISSUE TITLE
Implement user management features in front end

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#159]
Implement user management features in front end application
- [ ] Create / update / inactivate a user
- [ ] Create / update / delete a user group
- [ ] Add / remove user to a user group
- [ ] Send current user role `user_X` into JWT (see doc: https://www.graphile.org/postgraphile/jwt-guide)
- [ ] Send current user group `user_group_X` into JWT

**Comment by alexisrolland** [comment]
We also need to add a logout button.
