### ISSUE TITLE
Implement delete button (D from CRUD)

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#162]
- [x] ~Delete  button in overview / table~
- [x] Delete button in details

**Comment by alexisrolland** [comment]
I would suggest to just keep the delete button in details page to avoid mistake... it seems kind of easy to delete indicators accidentally in the list view.

**Comment by vilkazz** [comment]
aye, i could do that. But then i'll move the button to a different place to keep it away from submit/save button.

**Comment by vilkazz** [comment]
For now i implemented both buttons ( in list and in table) we can easily disable either one
