### ISSUE TITLE
Provide public demo of MobyDQ

### ISSUE THREAD

**Issue by PascalHonegger** [mobydq/mobydq#208]
As a developer I would like to have a usable demo version accessible in the internet. This would allow any developer to get a sense of the app without having to start up and configure his own instance. As the CI already builds the docker images it shouldn't be too hard to also deploy them to some sort of free host (e.g. I believe Google and AWS provide free hosting to some degree).

**Comment by alexisrolland** [comment]
Domain name purchased and public demo is now live at: http://mobydq.net
